import type { AccessAudienceDefinition, AccessModuleDefinition } from "./accessTypes";

export const ACCESS_AUDIENCES: readonly AccessAudienceDefinition[] = [
  {
    key: "public",
    label: "Public",
    shortLabel: "Public",
    description: "Alle besøgende uden login.",
  },
  {
    key: "member",
    label: "Member",
    shortLabel: "Member",
    description: "Loggede klubmedlemmer.",
  },
  {
    key: "clubAdmin",
    label: "Club admin",
    shortLabel: "Admin",
    description: "Klubadministratorer for den aktuelle tenant/club.",
  },
  {
    key: "platformAdmin",
    label: "Platform admin",
    shortLabel: "Platform",
    description: "Overordnet platformadministration på tværs af klubber.",
  },
] as const;

export const ACCESS_MODULES: readonly AccessModuleDefinition[] = [
  {
    key: "publicHome",
    label: "Public forside",
    area: "Public",
    description: "Offentlig klubforside med klubprofil, CTA, udvalgt offentligt indhold og sponsorer.",
    audiences: ["public", "member", "clubAdmin"],
    configurability: "fixed",
    note: "Skal sælge klubben og må ikke fungere som intern klubtavle.",
  },
  {
    key: "memberHome",
    label: "Member forside",
    area: "Member",
    description: "Aktivitetsdashboard for medlemmer med daglige klubfunktioner.",
    audiences: ["member", "clubAdmin"],
    configurability: "fixed",
    note: "Skal senere placeres separat fra public forsiden.",
  },
  {
    key: "about",
    label: "Om klubben",
    area: "Public",
    description: "Offentlig landing med bokse til klubbens underområder.",
    audiences: ["public", "member", "clubAdmin"],
    configurability: "fixed",
    note: "Underliggende sider kan senere få særskilt visibility.",
  },
  {
    key: "contact",
    label: "Kontakt",
    area: "Public",
    description: "Offentlig kontaktinfo, bestyrelse og instruktører med kontrollerede felter.",
    audiences: ["public", "member", "clubAdmin"],
    configurability: "fixed",
    note: "Kun bevidst eksponerede kontaktfelter må vises public.",
  },
  {
    key: "location",
    label: "Her bor vi",
    area: "Public",
    description: "Adresse, kort og praktisk info om flyvepladsen.",
    audiences: ["public", "member", "clubAdmin"],
    configurability: "fixed",
    note: "Public som klubprofil og praktisk besøgsinformation.",
  },
  {
    key: "membership",
    label: "Medlemskab / Bliv medlem",
    area: "Public",
    description: "Medlemsformer, kontingentinfo og offentlig ansøgningsformular.",
    audiences: ["public", "member", "clubAdmin"],
    configurability: "fixed",
    note: "Ansøgning er public; behandling sker i admin.",
  },
  {
    key: "flightSchool",
    label: "Flyveskole",
    area: "Public",
    description: "Offentlig præsentation af flyveskolen og hvordan man kommer i gang.",
    audiences: ["public", "member", "clubAdmin"],
    configurability: "fixed",
    note: "Booking og skolekalender er member/admin-funktioner.",
  },
  {
    key: "rules",
    label: "Regler og bestemmelser",
    area: "Public",
    description: "Regler, dokumenter og praktiske bestemmelser.",
    audiences: ["public", "member", "clubAdmin"],
    configurability: "contentVisibility",
    note: "Offentlige regler kan vises public; interne dokumenter skal være member-only.",
  },
  {
    key: "articles",
    label: "Artikler / nyheder",
    area: "Public",
    description: "Klubartikler, nyheder og redaktionelt indhold.",
    audiences: ["public", "member", "clubAdmin"],
    configurability: "contentVisibility",
    note: "Visibility bør styres pr. artikel.",
  },
  {
    key: "gallery",
    label: "Galleri",
    area: "Public",
    description: "Billeder og albums fra klubben.",
    audiences: ["public", "member", "clubAdmin"],
    configurability: "contentVisibility",
    note: "Visibility bør styres pr. album.",
  },
  {
    key: "calendar",
    label: "Kalender / marquee",
    area: "Public",
    description: "Kalenderpunkter og forside-marquee.",
    audiences: ["public", "member", "clubAdmin"],
    configurability: "contentVisibility",
    note: "Offentlige punkter public; interne aktiviteter member-only.",
  },
  {
    key: "sponsors",
    label: "Sponsorer",
    area: "Public",
    description: "Sponsorer og samarbejdspartnere vist i footer eller særskilt område.",
    audiences: ["public", "member", "clubAdmin"],
    configurability: "fixed",
    note: "Public som udgangspunkt.",
  },
  {
    key: "forum",
    label: "Forum",
    area: "Member",
    description: "Internt medlemsforum.",
    audiences: ["member", "clubAdmin"],
    configurability: "fixed",
    note: "Bør ikke gøres public. Eventuelt kun public teaser senere.",
  },
  {
    key: "iAmFlying",
    label: "Jeg flyver",
    area: "Member",
    description: "Daglig liste hvor medlemmer kan indikere flyveaktivitet.",
    audiences: ["member", "clubAdmin"],
    configurability: "fixed",
    note: "Intern aktivitetsfunktion. Ikke public.",
  },
  {
    key: "schoolBooking",
    label: "Skolebooking",
    area: "Member",
    description: "Booking af skoleflyvning og instruktørslots.",
    audiences: ["member", "clubAdmin"],
    configurability: "roleBased",
    note: "Public kan se flyveskoleinfo, men booking kræver login.",
  },
  {
    key: "memberDirectory",
    label: "Medlemsliste",
    area: "Member",
    description: "Oversigt over medlemmer og relevante kontaktfelter.",
    audiences: ["member", "clubAdmin"],
    configurability: "roleBased",
    note: "Privacy skal styres stramt. Ikke public.",
  },
  {
    key: "latestOnline",
    label: "Senest online",
    area: "Member",
    description: "Medlemsaktivitet og online-status.",
    audiences: ["member", "clubAdmin"],
    configurability: "future",
    note: "Kræver privacy-beslutning før implementering.",
  },
  {
    key: "internalMessages",
    label: "Interne beskeder",
    area: "Member",
    description: "Beskeder og intern information til medlemmer.",
    audiences: ["member", "clubAdmin"],
    configurability: "future",
    note: "Senere modul.",
  },
  {
    key: "adminDashboard",
    label: "Admin dashboard",
    area: "Club admin",
    description: "Driftsoverblik for den aktuelle klub.",
    audiences: ["clubAdmin"],
    configurability: "roleBased",
    note: "Tenant-scoped via clubId.",
  },
  {
    key: "siteSettings",
    label: "Site settings",
    area: "Club admin",
    description: "Klubnavn, logo, tema, koordinater og offentlige stamdata.",
    audiences: ["clubAdmin"],
    configurability: "roleBased",
    note: "Må kun påvirke aktuel klub.",
  },
  {
    key: "footerAdmin",
    label: "Footer administration",
    area: "Club admin",
    description: "Footerindhold, kontakt og sponsoropsætning.",
    audiences: ["clubAdmin"],
    configurability: "roleBased",
    note: "Må kun påvirke aktuel klub.",
  },
  {
    key: "memberAdmin",
    label: "Medlemsadministration",
    area: "Club admin",
    description: "Medlemmer, roller, medlemsstatus, instruktørflag og bestyrelse.",
    audiences: ["clubAdmin"],
    configurability: "roleBased",
    note: "Tenant-scoped og rollebeskyttet.",
  },
  {
    key: "memberApplications",
    label: "Medlemsansøgninger",
    area: "Club admin",
    description: "Ansøgning til behandling og senere konvertering til aktivt medlem.",
    audiences: ["clubAdmin"],
    configurability: "roleBased",
    note: "Næste større admin-flow før betaling/Dinero.",
  },
  {
    key: "mediaLibrary",
    label: "Media library",
    area: "Club admin",
    description: "Billeder, uploads og genbrug af media assets.",
    audiences: ["clubAdmin"],
    configurability: "roleBased",
    note: "Bør bruges som fælles media picker på tværs af admin.",
  },
  {
    key: "emailTemplates",
    label: "Email templates",
    area: "Club admin",
    description: "Skabeloner til notifikationer og standardmails.",
    audiences: ["clubAdmin"],
    configurability: "future",
    note: "Skal bygges før bred mailautomatisering.",
  },
  {
    key: "systemStatus",
    label: "Systemstatus",
    area: "Club admin",
    description: "Lokal klubstatus for mail, media, database og jobs.",
    audiences: ["clubAdmin"],
    configurability: "future",
    note: "Kommer efter admin dashboard foundation.",
  },
  {
    key: "payments",
    label: "Kontingent / betaling",
    area: "Club admin",
    description: "Kontingent, betaling, Dinero og afregning.",
    audiences: ["clubAdmin"],
    configurability: "future",
    note: "Senere fase.",
  },
  {
    key: "legacyImport",
    label: "Legacy import",
    area: "Club admin",
    description: "Import af eksisterende medlemmer, forum, billeder og artikler.",
    audiences: ["clubAdmin"],
    configurability: "future",
    note: "Senere kontrolleret importværktøj.",
  },
  {
    key: "platformDashboard",
    label: "Platform dashboard",
    area: "Platform admin",
    description: "Overblik over alle klubber og tenants.",
    audiences: ["platformAdmin"],
    configurability: "platformOnly",
    note: "Separat fra club admin.",
  },
  {
    key: "tenantAdmin",
    label: "Klubber / tenants",
    area: "Platform admin",
    description: "Opret, rediger, deaktivér og konfigurér klubber.",
    audiences: ["platformAdmin"],
    configurability: "platformOnly",
    note: "Må ikke blandes med EFK87 club admin.",
  },
  {
    key: "platformModules",
    label: "Modulstyring",
    area: "Platform admin",
    description: "Aktivér eller deaktivér moduler pr. klub.",
    audiences: ["platformAdmin"],
    configurability: "platformOnly",
    note: "Kommer senere som platformfunktion.",
  },
  {
    key: "platformFeatureFlags",
    label: "Feature flags",
    area: "Platform admin",
    description: "Overordnet feature control på tværs af tenants.",
    audiences: ["platformAdmin"],
    configurability: "platformOnly",
    note: "Kommer senere.",
  },
  {
    key: "platformThemeDefaults",
    label: "Tema defaults",
    area: "Platform admin",
    description: "Standardtemaer, farver og brandingpakker.",
    audiences: ["platformAdmin"],
    configurability: "platformOnly",
    note: "Kommer senere.",
  },
  {
    key: "platformOperations",
    label: "Platform drift",
    area: "Platform admin",
    description: "Global systemstatus, versioner, domæner og drift.",
    audiences: ["platformAdmin"],
    configurability: "platformOnly",
    note: "Kommer senere.",
  },
] as const;

export function hasAudience(module: AccessModuleDefinition, audienceKey: AccessAudienceDefinition["key"]): boolean {
  return module.audiences.includes(audienceKey);
}
