
import prisma from "@/lib/db/prisma";

export async function getPublicClubSettings(clubId: string) {
  return await prisma.clubSettings.findUnique({
    where: { clubId },
    select: {
      weatherLatitude: true,
      weatherLongitude: true,
      displayName: true,
      shortName: true,
      publicEmail: true,
      publicThemeMode: true,
          appleIconUrl: true,
      logoUrl: true,
      logoAltText: true,
      faviconUrl: true,
      publicHeroImageUrl: true,
      publicHeroImageAltText: true,
      publicHeroTitle: true,
      publicHeroSubtitle: true,
      publicHeroPrimaryCtaLabel: true,
      publicHeroPrimaryCtaHref: true,
      publicHeroSecondaryCtaLabel: true,
      publicHeroSecondaryCtaHref: true,
      publicHeroTertiaryCtaLabel: true,
      publicHeroTertiaryCtaHref: true,
      publicHeroQuaternaryCtaLabel: true,
      publicHeroQuaternaryCtaHref: true,
      publicIntroTitle: true,
      publicIntroLinkLabel: true,
      publicIntroLinkHref: true,
      publicIntroCard1Icon: true,
      publicIntroCard1Title: true,
      publicIntroCard1Text: true,
      publicIntroCard1Href: true,
      publicIntroCard2Icon: true,
      publicIntroCard2Title: true,
      publicIntroCard2Text: true,
      publicIntroCard2Href: true,
      publicIntroCard3Icon: true,
      publicIntroCard3Title: true,
      publicIntroCard3Text: true,
      publicIntroCard3Href: true,
      publicCtaSectionTitle: true,
      publicCtaSectionLinkLabel: true,
      publicCtaSectionLinkHref: true,
      publicCtaBoxIcon: true,
      publicCtaBoxTitle: true,
      publicCtaBoxText: true,
      publicCtaPrimaryLabel: true,
      publicCtaPrimaryHref: true,
      publicCtaSecondaryLabel: true,
      publicCtaSecondaryHref: true,
    }
  });
}
